### ISSUE TITLE
There is no unique inmplementation of the Service issue

### ISSUE THREAD

**Issue by eminach** [JPVenson/MSEF#1]
When I'm trying to launch the application getting this error from this line:
`var defaultSingelService = ServicePool.Instance.GetDefaultSingelService<IApplicationContainer>();`

`**System.NotImplementedException:** 'There is no unique inmplementation of the Service with the type : 
JPB.Shell.Contracts.Interfaces.Services.ApplicationServices.IApplicationContainer
The program can not Iditify one Module and tried to load the service but
 it allso does not found only one Defauld inplementation of the DefauldIncentFixerService.`

**Comment by JPVenson** [comment]
The most common case where this could happen is when:
You did not create an Implementation of IApplicationContainer in any imported Assembly.
Please check twice that:

- [ ] You have defined a priorityKey for fast lookup of your Assemblys
- [ ] You`r Implementation of IAppContainer is Public visible and in one of the Imported Assemblys
- [ ] You`r Implementation of IAppContainer has an ServiceExport Attribute

**Comment by eminach** [comment]
Thank you for reply
I have used this github solution just for test. 
What i am doing wrong? I must create own project and add nuget package? or
I should create new module with IAppContainer?
Thank you

**Comment by JPVenson** [comment]
You could do both. I Would recommend to create you`r own project with one start .exe where you search for the AppContainer and another DLL where you Implement it.

**Comment by eminach** [comment]
Thank you, but first I would like to start github sample
In this case `VisualMainWindow : IApplicationContainer` is public
What you think why GetDefaultSingelService can't find this module/service
PS. I unchecked VS "Only build startup projects and dependencies on RUN" and put it "Always"

**Comment by JPVenson** [comment]
Please try to debug through the exception and take a look if the VisualMainWindow was actually found in the list of services

**Comment by JPVenson** [comment]
Very good this is a very common error you could do ;-)

**Comment by JPVenson** [comment]
Oh ok. I just made a quick self test on the WPF Branch and it seems broken.
For a working simple example please try the Console branch

**Comment by eminach** [comment]
Thank you Pierre,
Yes I've tried Console, it works great 👍  Thanks for great job! 
Looking forward to hear WPF changes :)

**Comment by JPVenson** [comment]
You are welcome 👍 
i made a few changes but i cannot commit from my current place, so it might take 1 or 2 days.

I keep you in touch within this ticket.
If you got any other questions feel free to ask

**Comment by relliv** [comment]
After a few months and same error, please update.

**Comment by JPVenson** [comment]
@eminach @EgoistDeveloper this should do it
